### ISSUE TITLE
Pre-commit linting

### ISSUE THREAD

**Issue by Namchee** [Namchee/daily-watori#14]
## Overview

As stated from #4, anyone who committed to this repository must adhere to coding standards that have been set by `eslint`. However, the current solution requires contributors to run the `lint` process by themselves OR using the integrated [Visual Studio Code plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), which feels impractical for most cases.

This issue can be fixed by:

1. Add `lint` command to `package.json` that executes `eslint` directly
2. Add a `pre-commit` hook that executes the `lint` command.

**Comment by repurika** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/Namchee/daily-watori/releases/tag/v0.1.0) :rocket:
